# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: health.proto for package 'grpc_bug_demo'

require 'grpc'
require_relative 'health_pb'

module GrpcBugDemo
  module Health
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'grpc_bug_demo.Health'

      rpc :Check, HealthCheckRequest, HealthCheckResponse
      rpc :CheckFailure, HealthCheckRequest, HealthCheckResponse
    end

    Stub = Service.rpc_stub_class
  end
end
