# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grpc_bug_demo.HealthCheckRequest" do
    optional :service, :string, 1
    optional :loyalty_club_slug, :string, 2
  end
  add_message "grpc_bug_demo.HealthCheckResponse" do
    optional :status, :enum, 1, "grpc_bug_demo.HealthCheckResponse.ServingStatus"
  end
  add_enum "grpc_bug_demo.HealthCheckResponse.ServingStatus" do
    value :UNKNOWN, 0
    value :SERVING, 1
    value :NOT_SERVING, 2
  end
end

module GrpcBugDemo
  HealthCheckRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_bug_demo.HealthCheckRequest").msgclass
  HealthCheckResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_bug_demo.HealthCheckResponse").msgclass
  HealthCheckResponse::ServingStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_bug_demo.HealthCheckResponse.ServingStatus").enummodule
end
